# This will be the approach if you want to use a CD tool for deploying
# you will create a service account and get the service account's token and 
# then create kubeconfig file out of it.
# GKE does not support this approach(deprecated), this should work for EKS.
# kubeconfig skeleton is in file `sample-kubeconfig.yaml`, you just have to fill that.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-deploy
  namespace: go-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-deploy-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: github-deploy
  namespace: go-app
