apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: <LONG STRING>
    server: https://<API SERVER DNS/IP>
  name: go-app-cluster
users:
- name: app-deploy-user
  user:
    token: <SERVICE ACCOUNT TOKEN>
contexts:
- context:
    cluster: go-app-cluster
    user: app-deploy-user
  name: go-cluster-context

current-context:  go-cluster-context
