replicaCount: 1

deploymentConfig:
  containerPort: 8080

image:
  repository: dsdatsme/golanghttp
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: "go-app"
fullnameOverride: "go-app-deployment"

serviceAccount:
  create: true
  name: "go-app-sa"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: publicingress
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt-issuer
  hosts:
    - host: dsdatsme.ddns.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - dsdatsme.ddns.net
      secretName: dsdatsme-cert

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
