name: Build and Push Docker Image

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build Go Binary
        run: go build -o myserver
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to DockerHub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dsdatsme/golanghttp:latest
