name: golangci-lint
on:
  push:
  pull_request:
jobs:
  golang-list:
    name: lint-checker
    runs-on: ubuntu-latest
    steps:
      - name: Pulling code
        uses: actions/checkout@v2
      - name: Running the lint check on your files
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
