name: pull-request-validator
on: [pull_request, push, workflow_dispatch]
jobs:
  linter:
    name: lint-checker
    runs-on: ubuntu-latest
    steps:
      - name: Pulling code
        uses: actions/checkout@v2
      - name: Running unit tests
        run: |
          cd test && go test
          
